buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        gradlePluginPortal()
        maven{url 'https://jitpack.io'}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.android.tools:r8:8.2.33'
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0'
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:2.4.2")

    }
}


allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}


task clean(type: Delete) {
    delete rootProject.buildDir
}
